version: '3.8'

volumes:
  spire-agent-socket:

services:

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: spire
      POSTGRES_PASSWORD: spirepass
      POSTGRES_DB: spire
    ports:
      - "5432:5432"

  spire-server:
    image: ghcr.io/spiffe/spire-server:1.7.0
    volumes:
      - ./spire/server:/opt/spire/conf/server
    command: ["spire-server", "run"]
    ports:
      - "8081:8081"

  spire-agent:
    build: ./spire/agent
    depends_on:
      - spire-server
    volumes:
      - ./spire/agent:/opt/spire/conf/agent
      - spire-agent-socket:/tmp/spire-agent/public
    entrypoint: ["/opt/spire/bin/spire-agent"]
    pid: host
    command: ["run", "-config", "/opt/spire/conf/agent/agent.conf", "-joinToken", "<join_token>"]

  workload-server:
    build: ./workload/server
    volumes:
      - spire-agent-socket:/tmp/spire-agent/public:ro
    environment:
      - SPIFFE_ENDPOINT_SOCKET=/tmp/spire-agent/public/api.sock
    depends_on:
      - spire-agent
    command: ["./server"]
    pid: host
    ports:
      - "8443:8443"

  workload-client:
    build: ./workload/client
    volumes:
      - spire-agent-socket:/tmp/spire-agent/public
    environment:
      - SPIFFE_ENDPOINT_SOCKET=/tmp/spire-agent/public/api.sock
    depends_on:
      - workload-server
      - spire-agent
    user: "1000:1000"  
    command: ["./client"]


